{% set name = "cantok" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cantok-{{ version }}.tar.gz
  sha256: 0efc924f47d90851b8e83ed49170213ac76ff3da34b141d5d6db9f3fca6cde1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7

test:
  imports:
    - cantok
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/cantok
  doc_url: http://cantok.readthedocs.io/
  summary: Implementation of the "Cancellation Token" pattern
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
